[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fintrack-cli"
version = "1.0.0"
description = "Gestor de gastos pessoais com geração de gráficos via CLI"
readme = "README.md"
license = { text = "MIT" }

authors = [
    { name = "Luca Romariz", email = "luca.romariz@icloud.com" }
]

requires-python = ">=3.11"

dependencies = [
    "matplotlib>=3.8",
    "requests>=2.32",
    "psycopg2-binary>=2.9",
    "python-dotenv>=1.0"
]

[project.scripts]
fintrack = "fintrack.main:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=5.0",
    "ruff>=0.4",
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.setuptools]
packages = ["fintrack"]

[tool.setuptools.package-dir]
"" = "src"
